createOrReplace

	table financials
		lineageTag: 4158b95d-186b-4a29-b15b-1623931baf56

		column Segment
			dataType: string
			lineageTag: 1afcb9b2-b6c8-427a-aa25-dd49b7d70a74
			summarizeBy: none
			sourceColumn: Segment

			annotation SummarizationSetBy = Automatic

		column Country
			dataType: string
			lineageTag: 05ce783d-169b-4b0f-963f-4b3e331d3f5b
			summarizeBy: none
			sourceColumn: Country

			annotation SummarizationSetBy = Automatic

		column Product
			dataType: string
			lineageTag: 1912de7f-2bcd-4039-93a2-cbebe0c10a30
			summarizeBy: none
			sourceColumn: Product

			annotation SummarizationSetBy = Automatic

		column 'Discount Band'
			dataType: string
			lineageTag: ec65e3db-498c-4454-9027-834af4383c6f
			summarizeBy: none
			sourceColumn: Discount Band
			sortByColumn: 'Discount Band_ord'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Units Sold'
			dataType: double
			lineageTag: 9972246f-3d29-4f6c-8272-d8d38777db83
			summarizeBy: sum
			sourceColumn: Units Sold

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Manufacturing Price'
			dataType: int64
			formatString: 0
			lineageTag: 4b6ab42c-d986-4aad-a46e-c3ae25c3a871
			summarizeBy: sum
			sourceColumn: Manufacturing Price

			annotation SummarizationSetBy = Automatic

		column 'Sale Price'
			dataType: int64
			formatString: 0
			lineageTag: a286e583-ea56-4bde-bf49-d5b6051d0923
			summarizeBy: sum
			sourceColumn: Sale Price

			annotation SummarizationSetBy = Automatic

		column 'Gross Sales'
			dataType: double
			lineageTag: 4091dfa7-6654-4dc3-b924-dd769cbcb09d
			summarizeBy: sum
			sourceColumn: Gross Sales

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column Discounts
			dataType: double
			lineageTag: c71b145d-951e-4169-84f5-7190d62c6273
			summarizeBy: sum
			sourceColumn: Discounts

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column Sales
			dataType: double
			lineageTag: 53662205-e3d6-495d-9135-62094cb72a6a
			summarizeBy: sum
			sourceColumn: Sales

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column COGS
			dataType: double
			lineageTag: e405489a-0fcd-4bfe-ac72-ffbd95eb0bde
			summarizeBy: sum
			sourceColumn: COGS

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column Profit
			dataType: double
			lineageTag: 4c1541a1-f76c-4f9a-9a1a-3e5908277bdf
			summarizeBy: sum
			sourceColumn: Profit

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column Date
			dataType: dateTime
			formatString: Long Date
			lineageTag: 42845ba1-60a4-46c1-9a61-3a1728a426b5
			summarizeBy: none
			sourceColumn: Date

			variation Variation
				isDefault
				relationship: c7d48701-b403-4e02-a335-5956ade165f8
				defaultHierarchy: LocalDateTable_22bc4709-7451-4c9d-aa8f-9e01ef89fc91.'Date Hierarchy'

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		column 'Month Number'
			dataType: int64
			formatString: 0
			lineageTag: b821a732-bdfe-43de-a1ee-94c9b44a7634
			summarizeBy: sum
			sourceColumn: Month Number

			annotation SummarizationSetBy = Automatic

		column 'Month Name'
			dataType: string
			lineageTag: 9236b238-d3cb-4784-91a9-537b17942a5b
			summarizeBy: none
			sourceColumn: Month Name

			annotation SummarizationSetBy = Automatic

		column Year
			dataType: int64
			formatString: 0
			lineageTag: 59231a0b-e17d-48ff-b621-02ac445efe39
			summarizeBy: sum
			sourceColumn: Year

			annotation SummarizationSetBy = Automatic

		column 'Discount Band_ord'
			dataType: int64
			formatString: 0
			lineageTag: a926fe13-96a8-4719-8297-ff1f391a178e
			summarizeBy: sum
			sourceColumn: Discount Band_ord

			changedProperty = DataType

			annotation SummarizationSetBy = Automatic

		partition financials = m
			mode: import
			source =
					let
					 Source = Excel.Workbook(File.Contents("C:\Program Files\Microsoft Power BI Desktop\bin\SampleData\Financial Sample.xlsx"), null, true),
					    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
					    #"Changed Type" = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}}),
					    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Discount Band_ord", each if [Discount Band] = "None" then 1 else if [Discount Band] = "High" then 2 else if [Discount Band] = "Medium" then 3 else if [Discount Band] = "Low" then 4 else null)
					in
					 #"Added Conditional Column"

		annotation PBI_ResultType = Table

		annotation PBI_NavigationStepName = Navigation

